name = "eb-app-ui-ledger"
workers_dev = true
main = "./index.js"
compatibility_date = "2022-07-04"

[durable_objects]
bindings = [{name = "LEDGER_DO", class_name = "Ledger"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Ledger"]